### ISSUE TITLE
labelling 

### ISSUE THREAD

**Issue by xxchenchen** [nadimintikrish/semantic_segmentation_play#1]
Which program did you used for labelling the images?Thanks

**Comment by nadimintikrish** [comment]
Apologize for the long delayed response! just seen your comment over here. Thanks for taking a look over project.
Please find the dataset I have used for the project.

http://mi.eng.cam.ac.uk/research/projects/VideoRec/CamVid/data/LabeledApproved_full.zip

**Comment by xxchenchen** [comment]
Thanks
